# Data
data:
  train_dir: data/processed_data
# Preprocessing Pipeline
pipeline:
  name: Conv1DDataPipeline
  params:
    num_seconds: 10
# Model Architecture
model:
  name: RegConv1D
  params:
# Training Loop
training:
  training_loop:
    params:
      num_epochs: 500
      batch_size: 8
  optimizer:
    name: Adam
    params:
      learning_rate: .00001
# Float Params
float_params:
  -learning_rate
int_params:
  -batch_size
  -num_epochs
  -num_seconds
